modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
[[mods]]
modId = "clrcore"
version = "0.3-hotfix.2"
displayName = "CLR Core"
authors = "OneHumanAwa"
description = '''This core mod for Create: The Law of Rotation which can works standalone.
It also backports several features from Create Improve.
'''
[[dependencies."clrcore"]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."clrcore"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
[[dependencies."clrcore"]]
modId="create"
mandatory=true
versionRange="[6.0,6.1.0)"
ordering="NONE"
side="BOTH"